"""followers

Revision ID: 92272dd7b35c
Revises: 38dec5660f57
Create Date: 2018-08-30 16:59:14.725642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92272dd7b35c'
down_revision = '38dec5660f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
